### PR TITLE
🩹 Fixes incorrect refresh control visibility 

### LINKED ISSUE #4490: Dual progress bars on iPad
IMG_0058

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
Makes `TimelineViewController` a `UISplitViewControllerDelegate`.

- When the display mode is such that the feeds, timeline and article are visible, the timeline refresh control is hidden. 
- When the display mode is such that the timeline and article are visible, the timeline refresh control is visible.

Tested on iPad and iPhone 16 Pro Max (landscape).

Fixes #4490

### CODE REVIEW

File: iOS/MainTimeline/TimelineViewController.swift [hunk 1]
```diff
@@ -59,7 +59,10 @@ class TimelineViewController: UITableViewController, UndoableCommandRunner {
 		NotificationCenter.default.addObserver(self, selector: #selector(contentSizeCategoryDidChange), name: UIContentSizeCategory.didChangeNotification, object: nil)
 		NotificationCenter.default.addObserver(self, selector: #selector(displayNameDidChange), name: .DisplayNameDidChange, object: nil)
 		NotificationCenter.default.addObserver(self, selector: #selector(willEnterForeground(_:)), name: UIApplication.willEnterForegroundNotification, object: nil)
-
+		
+		// Split View Controller Delegate
+		splitViewController?.delegate = self
```
Comment (brentsimmons) [inline iOS/MainTimeline/TimelineViewController.swift:64]: The SceneCoordinator is the delegate for the splitViewController — so this fix should go in SceneCoordinator rather than in TimelineViewController

**Review by brentsimmons — CHANGES_REQUESTED** [review]

File: iOS/MainTimeline/TimelineViewController.swift (hunk 1 above)
Comment (stuartbreckenridge) [reply iOS/MainTimeline/TimelineViewController.swift]: Fixed in b5c592a

**Review by brentsimmons — APPROVED** [review]
